name: Release

# Controls when the action will run.
on:
  workflow_call:

jobs:
  # make a new version first, release or prerelease
  release:
    # Only run this job if new work is pushed to "main"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:

      - name: Checking out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup git user
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      # see *py_ver* in ci/update.py
      - name: Setting up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: |
            ci/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --progress-bar=off -r ci/requirements.txt

      - name: Determine a version number
        shell: sh
        run: |
          set -x
          # creates a release only if there are relevant changes/commits starting with 'fix/feat()'
          semantic-release publish -D version_source=commit \
            -D commit_author="${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
          if [ -z "$(git tag --points-at HEAD)" ]; then
            # no release, no relevant changes, make prerelease tag
            semantic-release version -D version_source=tag --prerelease
          fi
          git push
          git push --tags
